esphome:
  name: alvik-esphome
  friendly_name: alvik-esphome
  libraries:
    - ucPack

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  framework:
    type: arduino
  flash_size: 16MB
  partitions: /config/esphome/app3M_fat9M_fact512k_16MB.csv


debug:

# Enable logging
logger:
  hardware_uart: USB_CDC
  level: DEBUG
  logs:
    sensor: WARN
    text_sensor: WARN


# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  #use_address: 192.168.17.208
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid_backup
    password: !secret wifi_password
  ap:
    ssid: "Alvik_Nano_Fallback"
    password: !secret wifi_password
  domain: .lan


external_components:
  - source:
      type: git
      url: https://github.com/pipacsba/esphome_arduino_alvik.git
    #refresh: 1min
    refresh: 1days

arduino_alvik_esphome:
  id: "alvik_nano"
  #address: 0x36
  check_stm32_pin:
      number: GPIO13
      mode:
        input: true
        pulldown: true
  check_nano_pin: 
      number: GPIO07
      mode:
        output: true
  reset_stm32_pin: 
      number: GPIO06
      mode:
        output: true
  red_led:
      number: GPIO46
      mode:
        output: true
      ignore_strapping_warning: true
  green_led:
      number: GPIO00
      mode:
        output: true
      ignore_strapping_warning: true
  blue_led:
      number: GPIO45
      mode:
        output: true
      ignore_strapping_warning: true
  i2c_switch_1:
      number: GPIO03
      mode:
        output: true
      ignore_strapping_warning: true
  i2c_switch_2:
      number: GPIO04
      mode:
        output: true


sensor:
  - platform: "arduino_alvik_esphome"
    alvik_id: "alvik_nano"
    alvik_alive:
      name: alvik_alive
    alvik_action_state:
      name: alvik_action_state
    battery_charge:
      name: "battery"
      address: 0x36
    alvik_x_pose:
      name: alvik_x_pose
    alvik_y_pose:
      name: alvik_y_pose
    alvik_ang_pose:
      name: alvik_ang_pose
    alvik_roll:
      name: alvik_roll
    alvik_pitch:
      name: alvik_pitch
    alvik_yaw:
      name: alvik_yaw
    alvik_yaw_estimated:
      name: alvik_yaw_estimated
    joints_l:
      name: joints_l
    joints_r:
      name: joints_r
    joints_l_speed:
      name: joints_l_speed
    joints_r_speed:
      name: joints_r_speed
    distance_l:
      name: distance_l
    distance_cl:
      name: distance_cl
    distance_c:
      name: distance_c
    distance_cr:
      name: distance_cr
    distance_r:
      name: distance_r
    distance_t:
      name: distance_t
    distance_b:
      name: distance_b
    compass_direction:
      name: compass_direction
    compass_x:
      name: compass_x
    compass_y:
      name: compass_y
    compass_z:
      name: compass_z
    tof_centoid:
      name: tof_centoid
    received_messages_counter:
      name: received_messages_counter
    follow_start:
      name: follow_start
    constant_direction_start:
      name: constant_direction_start
    maze_solver_start:
      name: maze_solver_start
    maze_crawling_state:
      name: maze_crawling_state
    line_sensor_left:
      name: line_sensor_left
    line_sensor_center:
      name: line_sensor_center
    line_sensor_right:
      name: line_sensor_right
    maze_solved_bool:
      name: maze_solved_bool

     

text_sensor:
  - platform: "arduino_alvik_esphome"
    alvik_id: "alvik_nano"
    command_list:
      name: command_list
    maze_descriptor_sensor:
      name: maze_descriptor_sensor
    maze_solution_descriptor_sensor:
      name: maze_solution_descriptor_sensor
#    firmware_version:
#      name: "firmware version"
#    library_version:
#      name: "library version"

switch:
  - platform: "arduino_alvik_esphome"
    alvik_id: "alvik_nano"
    enable_alvik:
      name: load alvik

uart:  # config=SERIAL_8N1
  id: stm_bus
  baud_rate: 460800  #115200
  rx_pin: GPIO44
  tx_pin: GPIO43
  parity: NONE
  stop_bits: 1

button:
  - platform: "arduino_alvik_esphome"
    alvik_id: "alvik_nano"
    move_forward:
      name: "Forward"
    move_backwards:
      name: "Backwards"
    turn_left:
      name: "Left turn"
    turn_right:
      name: "Right turn"
    ok:
      name: "OK"
    cancel:
      name: "Cancel"
    center:
      name: "Center"
    hw_reset:
      name: "hw_reset"
    reset_pose:
      name: "reset pose"


number:
  - platform: "arduino_alvik_esphome"
    alvik_id: "alvik_nano"
    move_forward_distance:
      name: "move_forward_distance"
      mode: BOX
    turn_degree:
      name: "turn_degree"
      mode: BOX
    follow_distance:
      name: "follow_distance"
      mode: BOX
    follow_tolerance:
      name: "follow_tolerance"
      mode: BOX
    follow_gain_horizontal:
      name: "follow_gain_horizontal"
      mode: BOX
    follow_gain_front:
      name: "follow_gain_front"
      mode: BOX
    constant_direction_gain:
      name: "constant_direction_gain"
      mode: BOX
    constant_direction_target:
      name: constant_direction_target
      mode: BOX
    line_follower_p:
      name: line_follower_p
      mode: BOX
    line_follower_i:
      name: line_follower_i
      mode: BOX
    line_follower_d:
      name: line_follower_d
      mode: BOX
    maze_crawling_speed:
      name: maze_crawling_speed
      mode: BOX

i2c:
  sda: GPIO11
  scl: GPIO12
  scan: false
  id: battery_bus
