esphome:
  name: arduino-alvik
  friendly_name: arduino-alvik
  libraries:
    - Wire
    - EEPROM
    - ucPack
#    - Arduino_Alvik
        
esp32:
  #board: arduino_nano_esp32
  # https://github.com/esphome/esphome/discussions/6325
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Arduino-Alvik Fallback Hotspot"

external_components:
  - source:
      type: git
      url: https://github.com/pipacsba/esphome_arduino_alvik.git
    refresh: 1min
    #refresh: 1days


arduino_alvik_esphome:
